_wandb:
    value:
        cli_version: 0.23.0
        e:
            gfdlaogp5azep6rwjgczguy3rouxpamq:
                codePath: ZNEUS_Project_2\src\main.py
                codePathLocal: main.py
                email: xbrutovskyf@stuba.sk
                executable: C:\Users\filip\miniconda3\envs\torch310\python.exe
                git:
                    commit: 5e9f8b39c0fa6a4051351077bef53fdc25f78d29
                    remote: https://github.com/AweFilko/ZNEUS_R-B.git
                host: Filkos_asus
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\filip\PycharmProjects\ZNEUS_R&B\ZNEUS_R-B\ZNEUS_Project_2\src\main.py
                python: CPython 3.10.19
                root: C:\Users\filip\PycharmProjects\ZNEUS_R&B\ZNEUS_R-B\ZNEUS_Project_2\src
                startedAt: "2025-11-28T21:06:14.260120Z"
                writerId: gfdlaogp5azep6rwjgczguy3rouxpamq
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
            "4": 3.10.19
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
model_hyperparams:
    value:
        batch_size: 128
        dropout: 0.25
        epochs: 20
        learning_rate: 0.001
        weight_decay: "5e-4"
setup:
    value:
        debug: true
        device: cuda
        df_file: sports.csv
        img_size: (224,224)
        sport:
            - sumo wrestling
            - water polo
            - ski jumping
            - chuckwagon racing
            - cheerleading
            - canoe slamon
            - formula 1 racing
            - fly fishing
            - bungee jumping
            - rock climbing
            - pole dancing
            - track bicycle
            - hurdles
            - uneven bars
        transform:
            color_jitter:
                brightness: 0.2
                contrast: 0.2
                hue: 0.1
                saturation: 0.2
            horizontal_flip_prob: 0.5
            normalization: true
            random_rotation_degree: 30
