setup:
  df_file: "sports.csv"
  debug: True
  device: "cuda" #"cpu"
  img_size: (224,224)
  sport:
    - "sumo wrestling"
    - "water polo"
    - "ski jumping"
    - "chuckwagon racing"
    - "cheerleading"
    - "canoe slamon"
    - "formula 1 racing"
    - "fly fishing"
    - "bungee jumping"
    - "rock climbing"
    - "pole dancing"
    - "track bicycle"
    - "hurdles"
    - "uneven bars"
  transform:
    horizontal_flip_prob: 0.3
    random_rotation_degree: 15
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    normalization: True
model_hyperparams:
  batch_size: 32
  epochs: 30
  learning_rate: 0.0005
  weight_decay: 5e-4
  dropout: 0.2
  mode: min
  factor: 0.5
  patience: 2
model: 3 # 0: simpleCNN \ 1: deepCNN \ 2: ResNet \ 3: FENN
train: 0 # 0: complex_train \ 1: simple_train



