setup:
  df_file: "sports.csv"
  debug: True
  device: "cuda" #"cpu"
  img_size: (224,224)
  sport:
    - "sumo wrestling"
    - "water polo"
    - "ski jumping"
    - "chuckwagon racing"
    - "cheerleading"
    - "canoe slamon"
    - "formula 1 racing"
    - "fly fishing"
    - "bungee jumping"
    - "rock climbing"
    - "pole dancing"
    - "track bicycle"
    - "hurdles"
    - "uneven bars"
  transform:
    horizontal_flip_prob: 0.5
    random_rotation_degree: 30
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    normalization: True
model_hyperparams:
  batch_size: 256
  epochs: 10
  learning_rate: 0.001




